-- =====================================================================
-- BAIREN · Portal · unidades cargadas en la web después de la carga inicial del 4/9
--
-- Generado el 2026-09-10 desde la base de la web (public.propiedades, publicadas),
-- con la misma lógica de portal/js/data.js y el mismo formato de seed-avisos.sql.
-- Trae las 4 unidades que faltaban en el portal: Húsares 1080 1º, Figueroa Alcorta
-- 3000 2 y 3300 2 (los lofts del Palacio Alcorta) y Av. Gral las Heras 2371 10 B.
--
-- Pasos: SQL Editor del proyecto del portal -> pegar todo -> Run. Se puede correr
-- más de una vez (on conflict do nothing). Requiere schema-portal.sql y seed-avisos.sql.
-- =====================================================================

do $seed$
declare v_pub uuid; v_aviso uuid;
begin
  select id into v_pub from portal.publicadores where slug = 'maxim-rentals';
  if v_pub is null then
    raise exception 'falta el publicador maxim-rentals: corré antes portal/schema-portal.sql';
  end if;

  -- Húsares 1080 · 1º · mediano
  insert into portal.avisos (codigo, slug, publicador_id, propiedad_id, operacion, titulo, direccion, unidad, barrio, zona, precio, m2_total, m2_cubierto, ambientes, dormitorios, banos, amoblado, amenities, descripcion, descripcion_en, descripcion_pt, video_url, video_tipo, plazo, estado, estado_curacion, publicado_en)
  values ('BA-HUSARES10801M', 'husares-1080-1', v_pub, '87cc3c1d-545f-4ae5-9090-a799d01153f9', 'mediano', 'Húsares 1080 · 1º', 'Húsares 1080', '1º', 'San Isidro', 'San Isidro', 3500, 150, 150, 4, 3, 2, true, '{"Aire acondicionado","Bicicletero","Calefacción central","Cochera","Terraza o jardín","Laundry","Parrilla","Pet friendly","Pileta","Seguridad 24hs"}'::text[], 'Casa de 4 ambientes con jardín privado y piscina en San Isidro. A metros del Río y de los clubes náuticos más tradicionales de Zona Norte. 150 m² amoblados con espacios amplios, luz natural en todos los ambientes y la tranquilidad que solo da vivir rodeado de verde. Servicios y mantenimiento de la propiedad totalmente incluidos dentro del presupuesto.', 'Three-bedroom house with private garden and pool in San Isidro. Steps from the river and the most traditional yacht clubs of the northern suburbs. 150 m² furnished, with generous spaces, natural light in every room and the peace that only comes from living surrounded by green. Utilities and property maintenance fully included in the budget.', 'Casa de 4 ambientes com jardim privado e piscina em San Isidro. A poucos metros do rio e dos clubes náuticos mais tradicionais da Zona Norte. 150 m² mobiliados, com espaços amplos, luz natural em todos os ambientes e a tranquilidade que só se tem morando rodeado de verde. Serviços e manutenção do imóvel totalmente incluídos no orçamento.', null, null, '3-12 meses', 'reservado', 'publicado', '2026-05-22T13:37:21.560204+00:00')
  on conflict (codigo) do nothing
  returning id into v_aviso;
  if v_aviso is null then select id into v_aviso from portal.avisos where codigo = 'BA-HUSARES10801M'; end if;
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/husares-1080-1/foto-1.jpg', 0 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/husares-1080-1/foto-1.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/husares-1080-1/foto-2.jpg', 1 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/husares-1080-1/foto-2.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/husares-1080-1/foto-3.jpg', 2 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/husares-1080-1/foto-3.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/husares-1080-1/foto-4.jpg', 3 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/husares-1080-1/foto-4.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/husares-1080-1/foto-5.jpg', 4 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/husares-1080-1/foto-5.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/husares-1080-1/foto-6.jpg', 5 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/husares-1080-1/foto-6.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/husares-1080-1/foto-7.jpg', 6 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/husares-1080-1/foto-7.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/husares-1080-1/foto-8.jpg', 7 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/husares-1080-1/foto-8.jpg');

  -- Figueroa Alcorta 3000 · 2 · venta
  insert into portal.avisos (codigo, slug, publicador_id, propiedad_id, operacion, titulo, direccion, unidad, barrio, zona, precio, m2_total, m2_cubierto, ambientes, dormitorios, banos, amoblado, amenities, descripcion, descripcion_en, descripcion_pt, video_url, video_tipo, plazo, estado, estado_curacion, publicado_en)
  values ('BA-FIGUEROAALCORTA30002V', 'figueroa-alcorta-3000-2', v_pub, '3342e4e5-6262-48ad-bb26-e3d499b293c6', 'venta', 'Figueroa Alcorta 3000 · 2', 'Figueroa Alcorta 3000', '2', 'Palermo Chico', 'Palermo Chico', 650000, 110, 110, 2, 1, 1, true, '{"Aire acondicionado","Amoblado","Ascensor","Bicicletero","Calefacción central","Cochera","Conserje 24hs","Gimnasio","Terraza o jardín","Laundry","Parrilla","Pet friendly","Pileta","Seguridad 24hs","Spa / Sauna"}'::text[], 'Loft de 110 m² con cochera en el Palacio Alcorta. Ex edificio Chrysler proyectado por Mario Palanti.
Incluye 1 cochera. Opcional cochera doble +$50.000usd.

Una sola planta de techos altos, con dos columnas que ordenan el espacio sin dividirlo y piso de travertino en todos los ambientes. Living con doble estar, cocina integrada en madera oscura con barra de vidrio y cava para 100 botellas.
Toilette de recepción, dormitorio con vestidor y baño en mármol de Carrara con hidromasaje.

El edificio ocupa una manzana entera de Palermo Chico, con el MALBA cruzando la calle: pileta climatizada con solárium, gimnasio con pilates, spa con sauna, laundry y seguridad 24 horas.

Las superficies y medidas son aproximadas y surgirán del título de propiedad respectivo.
Corredor responsable: Maximiliano Matzkin, Matrícula CUCICBA Nº 7527, Maxim Rentals.', '110 m² loft with double garage in the Alcorta Palace. the former Chrysler building from 1928 designed by Mario Palanti, the architect of the Barolo Palace. Where the roof test track was, today there is an oval garden with a heated pool, and the unit looks exactly there from the dining room gallery.

A single floor with high ceilings, with two columns that organize the space without dividing it and travertine floors in all rooms. Living room with double living room, integrated kitchen in dark wood with glass bar and cellar for 100 bottles.
Reception toilet, bedroom with dressing room and Carrara marble bathroom with hydromassage.

The building occupies an entire block of Palermo Chico, with the MALBA across the street: heated pool with solarium, gym with Pilates, spa with sauna, laundry and 24-hour security.

The surfaces and measurements are approximate and will arise from the respective property title.
Responsible broker: Maximiliano Matzkin, CUCICBA Registration No. 7527, Maxim Rentals.', 'Loft de 110 m² com garagem dupla no Palácio de Alcorta. o antigo edifício da Chrysler de 1928 projetado por Mario Palanti, o arquiteto do Palácio Barolo. Onde ficava a pista de testes da cobertura, hoje existe um jardim oval com piscina aquecida, e o aparelho fica exatamente ali visto da galeria da sala de jantar.

Piso único com pé direito alto, com duas colunas que organizam o espaço sem dividi-lo e piso de travertino em todos os ambientes. Sala com sala dupla, cozinha integrada em madeira escura com balcão de vidro e adega para 100 garrafas.
WC de recepção, quarto com closet e casa de banho em mármore Carrara com hidromassagem.

O prédio ocupa um quarteirão inteiro do Palermo Chico, com o MALBA do outro lado da rua: piscina climatizada com solário, academia com Pilates, spa com sauna, lavanderia e segurança 24 horas.

As superfícies e medidas são aproximadas e decorrerão do respetivo título de propriedade.
Corretor responsável: Maximiliano Matzkin, Registro CUCICBA nº 7527, Maxim Rentals.', null, null, null, 'disponible', 'publicado', '2026-09-04T13:35:56.894553+00:00')
  on conflict (codigo) do nothing
  returning id into v_aviso;
  if v_aviso is null then select id into v_aviso from portal.avisos where codigo = 'BA-FIGUEROAALCORTA30002V'; end if;
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/portada-catalogo-1788539069090.jpg', 0 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/portada-catalogo-1788539069090.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-1-1788528956810.jpg', 1 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-1-1788528956810.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-2-1788528958562.jpg', 2 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-2-1788528958562.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-3-1788528959575.jpg', 3 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-3-1788528959575.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-4-1788528960501.jpg', 4 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-4-1788528960501.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-21-1788532699877.jpg', 5 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-21-1788532699877.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-6-1788528963459.jpg', 6 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-6-1788528963459.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-22-1788532701001.jpg', 7 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-22-1788532701001.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-8-1788528964891.jpg', 8 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-8-1788528964891.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-9-1788528968313.jpg', 9 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-9-1788528968313.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-10-1788528970029.jpg', 10 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-10-1788528970029.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-12-1788528972992.jpg', 11 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-12-1788528972992.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-13-1788528974146.jpg', 12 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-13-1788528974146.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-14-1788528974985.jpg', 13 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-14-1788528974985.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-15-1788528975983.jpg', 14 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-15-1788528975983.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-16-1788528976871.jpg', 15 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-16-1788528976871.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-17-1788528977559.jpg', 16 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-17-1788528977559.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-18-1788528978597.jpg', 17 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-18-1788528978597.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-19-1788528980467.jpg', 18 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-19-1788528980467.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-20-1788528981908.jpg', 19 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3000-2/foto-20-1788528981908.jpg');

  -- Figueroa Alcorta 3300 · 2 · alquiler
  insert into portal.avisos (codigo, slug, publicador_id, propiedad_id, operacion, titulo, direccion, unidad, barrio, zona, precio, m2_total, m2_cubierto, ambientes, dormitorios, banos, amoblado, amenities, descripcion, descripcion_en, descripcion_pt, video_url, video_tipo, plazo, estado, estado_curacion, publicado_en)
  values ('BA-FIGUEROAALCORTA33002L', 'figueroa-alcorta-3300-2', v_pub, '2c69b317-911b-4476-8ccb-205e53a05b92', 'alquiler', 'Figueroa Alcorta 3300 · 2', 'Figueroa Alcorta 3300', '2', 'Palermo Chico', 'Palermo Chico', 3500, 110, 110, 2, 1, 1, false, '{}'::text[], 'Loft de 110 m² en el Palacio Alcorta. Ex edificio Chrysler proyectado por Mario Palanti.
- Valor de expensas $1.800.000 ARS
- Incluye 2 cocheras.

Una sola planta de techos altos, con dos columnas que ordenan el espacio sin dividirlo y piso de travertino en todos los ambientes. Living con doble estar, cocina integrada en madera oscura con barra de vidrio y cava para 100 botellas.
Toilette de recepción, dormitorio con vestidor y baño en mármol de Carrara con hidromasaje.

El edificio ocupa una manzana entera de Palermo Chico, con el MALBA cruzando la calle: pileta climatizada con solárium, gimnasio con pilates, spa con sauna, laundry y seguridad 24 horas.

Las superficies y medidas son aproximadas y surgirán del título de propiedad respectivo.
Corredor responsable: Maximiliano Matzkin, Matrícula CUCICBA Nº 7527, Maxim Rentals.', '110 m² loft with garage in the Alcorta Palace. Former Chrysler building designed by Mario Palanti.
Includes 1 garage. Optional double garage +$50,000usd.

A single floor with high ceilings, with two columns that organize the space without dividing it and travertine floors in all rooms. Living room with double living room, integrated kitchen in dark wood with glass bar and cellar for 100 bottles.
Reception toilet, bedroom with dressing room and Carrara marble bathroom with hydromassage.

The building occupies an entire block of Palermo Chico, with the MALBA across the street: heated pool with solarium, gym with Pilates, spa with sauna, laundry and 24-hour security.

The surfaces and measurements are approximate and will arise from the respective property title.
Responsible broker: Maximiliano Matzkin, CUCICBA Registration No. 7527, Maxim Rentals.', 'Loft de 110 m² com garagem no Palácio de Alcorta. Antigo edifício da Chrysler projetado por Mario Palanti.
Inclui 1 garagem. Garagem dupla opcional +$50.000usd.

Piso único com pé direito alto, com duas colunas que organizam o espaço sem dividi-lo e piso de travertino em todos os ambientes. Sala com sala dupla, cozinha integrada em madeira escura com balcão de vidro e adega para 100 garrafas.
WC de recepção, quarto com closet e casa de banho em mármore Carrara com hidromassagem.

O prédio ocupa um quarteirão inteiro do Palermo Chico, com o MALBA do outro lado da rua: piscina climatizada com solário, academia com Pilates, spa com sauna, lavanderia e segurança 24 horas.

As superfícies e medidas são aproximadas e decorrerão do respetivo título de propriedade.
Corretor responsável: Maximiliano Matzkin, Registro CUCICBA nº 7527, Maxim Rentals.', null, null, 'A partir de 2 años', 'disponible', 'publicado', '2026-09-04T16:21:57.129821+00:00')
  on conflict (codigo) do nothing
  returning id into v_aviso;
  if v_aviso is null then select id into v_aviso from portal.avisos where codigo = 'BA-FIGUEROAALCORTA33002L'; end if;
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/portada-catalogo-1788539080940.jpg', 0 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/portada-catalogo-1788539080940.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-1-1788538917065.jpg', 1 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-1-1788538917065.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-2-1788538918184.jpg', 2 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-2-1788538918184.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-3-1788538918800.jpg', 3 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-3-1788538918800.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-4-1788538919619.jpg', 4 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-4-1788538919619.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-5-1788538920299.jpg', 5 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-5-1788538920299.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-6-1788538921052.jpg', 6 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-6-1788538921052.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-7-1788538921731.jpg', 7 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-7-1788538921731.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-8-1788538922430.jpg', 8 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-8-1788538922430.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-9-1788538923131.jpg', 9 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-9-1788538923131.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-10-1788538923817.jpg', 10 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-10-1788538923817.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-11-1788538924425.jpg', 11 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-11-1788538924425.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-12-1788538925116.jpg', 12 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-12-1788538925116.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-13-1788538925772.jpg', 13 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-13-1788538925772.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-14-1788538926377.jpg', 14 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-14-1788538926377.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-15-1788538927102.jpg', 15 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-15-1788538927102.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-16-1788538927708.jpg', 16 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-16-1788538927708.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-17-1788538928320.jpg', 17 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-17-1788538928320.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-18-1788538928948.jpg', 18 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/figueroa-alcorta-3300-2/foto-18-1788538928948.jpg');

  -- Av. Gral las Heras 2371 · 10 B · mediano
  insert into portal.avisos (codigo, slug, publicador_id, propiedad_id, operacion, titulo, direccion, unidad, barrio, zona, precio, m2_total, m2_cubierto, ambientes, dormitorios, banos, amoblado, amenities, descripcion, descripcion_en, descripcion_pt, video_url, video_tipo, plazo, estado, estado_curacion, publicado_en)
  values ('BA-AVGRALLASHERAS237110BM', 'av-gral-las-heras-2371-10-b', v_pub, '4a550311-0c7b-4dcb-9405-3fbb9bac854b', 'mediano', 'Av. Gral las Heras 2371 · 10 B', 'Av. Gral las Heras 2371', '10 B', 'Recoleta', 'Recoleta', 1000, 35, 35, 2, 1, 1, true, '{"Aire acondicionado","Amoblado","Ascensor","Pet friendly"}'::text[], 'Dos ambientes de 35 m² en un décimo piso de Recoleta, con balcón al frente, vista abierta y parquet en toda la unidad. 
Amoblado y equipado, con expensas y servicios incluidos en el precio paquete.

• Living comedor con salida a balcón por ventanal corredizo y ventana de paso a la cocina
• Balcón al frente, con lugar para mesa baja y dos sillas, vista abierta a la ciudad
• Dormitorio con ventana corrediza y vista abierta, escritorio de línea moderna con estante alto y mueble bajo con puertas
• Cocina independiente tipo pasillo, con azulejos de época en blanco y azul, mesada de acero con bacha doble, cocina a gas con horno, alacenas y bajo mesada
• Sector de servicio al fondo de la cocina, con termotanque a gas y espacio de tendido
• Toilette y baño completo con bañera, bidet, inodoro y bacha con pie, el juego entero en rosa de época, azulejos hasta el techo y piso de granito negro
• Parquet en espina de pez en living y dormitorio', 'Two 35 m² rooms on the tenth floor of Recoleta, with a balcony in front, open views and parquet throughout the unit. 
Furnished and equipped, with expenses and services included in the package price.

• Living room with access to a balcony through a sliding window and a window leading to the kitchen.
• Balcony in front, with place for a low table and two chairs, open view of the city
• Bedroom with sliding window and open view, modern desk with high shelf and low cabinet with doors
• Independent hallway-type kitchen, with period tiles in white and blue, steel countertop with double sink, gas stove with oven, cupboards and under counter.
• Service area at the back of the kitchen, with gas water heater and storage space.
• Toilette and full bathroom with bathtub, bidet, toilet and sink with foot, the entire set in vintage pink, tiles to the ceiling and black granite floor
• Herringbone parquet in living room and bedroom', 'Dois quartos de 35 m² no décimo andar da Recoleta, com varanda frontal, vista panorâmica e piso em parquet em toda a unidade. 
Mobilado e equipado, com despesas e serviços incluídos no preço do pacote.

• Sala com acesso a varanda através de janela de correr e janela de acesso à cozinha.
• Varanda na frente, com lugar para uma mesa baixa e duas cadeiras, vista aberta para a cidade
• Quarto com janela de correr e vista aberta, mesa moderna com prateleira alta e armário baixo com portas
• Cozinha independente tipo corredor, com azulejos de época nas cores branco e azul, bancada em aço com pia dupla, fogão a gás com forno, armários e embaixo da bancada.
• Área de serviço nos fundos da cozinha, com esquentador a gás e arrecadação.
• WC e WC completo com banheira, bidé, sanita e lavatório com pé, todo o conjunto em rosa vintage, azulejos até ao teto e piso em granito preto
• Parquet espinha de peixe na sala de estar e no quarto', null, null, '3-12 meses', 'disponible', 'publicado', '2026-09-08T21:06:23.760782+00:00')
  on conflict (codigo) do nothing
  returning id into v_aviso;
  if v_aviso is null then select id into v_aviso from portal.avisos where codigo = 'BA-AVGRALLASHERAS237110BM'; end if;
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/portada-catalogo-1788901891324.jpg', 0 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/portada-catalogo-1788901891324.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/foto-1-1788901583655.jpg', 1 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/foto-1-1788901583655.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/foto-2-1788901584309.jpg', 2 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/foto-2-1788901584309.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/foto-3-1788901585004.jpg', 3 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/foto-3-1788901585004.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/foto-4-1788901585829.jpg', 4 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/foto-4-1788901585829.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/foto-5-1788901586514.jpg', 5 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/foto-5-1788901586514.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/foto-6-1788901586994.jpg', 6 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/foto-6-1788901586994.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/foto-7-1788901587464.jpg', 7 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/foto-7-1788901587464.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/foto-8-1788901587993.jpg', 8 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/foto-8-1788901587993.jpg');
  insert into portal.fotos (aviso_id, url, orden) select v_aviso, 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/foto-9-1788901588514.jpg', 9 where not exists (select 1 from portal.fotos where aviso_id = v_aviso and url = 'https://nmrjyyrhwjroonrppnka.supabase.co/storage/v1/object/public/imagenes-propiedades/av-gral-las-heras-2371-10-b/foto-9-1788901588514.jpg');

end $seed$;
