/* A · Gestor de alquileres, mediano plazo con disponible desde y qué incluye, desde cero (sin sesión), en celular o compu */
import { conectar, sleep } from './cdp.mjs';
import { limpiar, pantalla, seguir, set, chip, marcar, pasos, medir, fotos, avisos, pubs, toast, DESC, FOTOS, ingresarLocal, esperar } from './flujo.mjs';
const c = await conectar(); const mob = process.argv[2] !== 'desktop'; await c.vista(mob); const P = (mob ? 'm' : 'd') + '-mediano-';
const out = { medidas: [] }; const m = async (n) => { const x = await medir(c); out.medidas.push(x); await c.foto(P + n); return x; };
await limpiar(c);
await c.ir('publicar-aviso.html?perfil=gestor', 1200);
out.sinSesion = await pantalla(c);
await m('1-que');
await c.ev('document.querySelector("[data-que=mediano]").click(); true');
await seguir(c, 300);
out.fueAIngresar = await c.ev('location.pathname + location.search');
await ingresarLocal(c, 'gestor.p2@ejemplo.com');
out.volvio = await c.ev('location.pathname + location.search') + ' / ' + await esperar(c, 'empresa');
await m('3-empresa');
out.empresaTipo = await c.ev('(document.querySelector("[name=tipo_pub]:checked")||{}).value');
await set(c, { nombre: 'Gestora Mediano', whatsapp: '11 2345 6789', cuit: '30-71234567-8' });
await seguir(c);
out.pub = (await pubs(c)).map(p => [p.tipo, p.nombre, p.whatsapp, p.telefono, p.cuit, p.badge].join(' | '));
out.p4 = await pantalla(c);
await m('4-propiedad-vacia');
await set(c, { zona: 'Retiro' }); await sleep(100);
out.barrioRetiro = await c.ev('document.getElementById("f-barrio").value');
await set(c, { direccion: 'Arenales 1000', unidad: '5 A', m2_total: '45' });
await pasos(c, 'ambientes', 2); await pasos(c, 'banos', 1);
await m('4-propiedad');
await seguir(c);
out.borrador1 = (await avisos(c)).map(a => [a.direccion, a.unidad, a.zona, a.barrio, a.operacion, a.ambientes, a.banos, a.m2_total, a.estado_curacion].join(' | '));
out.p5 = await pantalla(c);
await m('5-precio');
// sin estadía: error
await set(c, { precio: '1400' });
await seguir(c, 500); out.sinEstadia = await toast(c) + ' / ' + await pantalla(c);
await c.foto(P + '5-precio-error');
await chip(c, 'plazo', '3 meses');
await set(c, { disponible_desde: '2026-11-01' });
await marcar(c, 'incl', ['Expensas incluidas', 'Servicios incluidos', 'Internet incluido']);
out.expensasOculta = await c.ev('document.querySelector("[data-fld=expensas]").hidden');
await m('5-precio-lleno');
await seguir(c);
out.borrador2 = (await avisos(c)).map(a => [a.precio, a.moneda, a.plazo, a.disponible_desde, (a.caracteristicas||[]).join('+'), a.expensas].join(' | '));
out.p6 = await pantalla(c);
await m('6-fotos-vacia');
out.nFotos = await fotos(c, FOTOS.slice(0, 8));
await m('6-fotos');
out.fotosGuardadas = (await avisos(c)).map(a => a.fotos.length);
// mover la última a portada con el menú
await c.ev('document.querySelector("[data-menu=\'7\']").click(); true'); await sleep(500);
await c.foto(P + '6-fotos-menu');
out.hoja = await c.ev('document.querySelector(".pf-hoja-caja").innerText.replace(/\\n+/g," / ")');
const ultima = (await avisos(c))[0].fotos[7].url;
await c.ev('document.querySelector(".pf-hoja [data-portada]").click(); true'); await sleep(900);
out.portadaMovida = (await avisos(c))[0].fotos[0].url === ultima;
await seguir(c);
out.p7 = await pantalla(c);
await m('7-descripcion-vacia');
await set(c, { descripcion: DESC });
await marcar(c, 'lqt', ['Amoblado', 'Balcón', 'Seguridad 24hs', 'Apto profesional', 'Pet friendly']);
await m('7-descripcion');
await seguir(c, 1500);
out.borrador3 = (await avisos(c)).map(a => ({ amen: a.amenities, car: a.caracteristicas, amoblado: a.amoblado, desc: a.descripcion.length }));
out.p8 = await pantalla(c);
await m('8-revisar');
await c.foto(P + '8-revisar-completa', true);
out.resumen = await c.ev('document.querySelector(".pf-resumen").innerText.replace(/\\n+/g," / ")');
await seguir(c, 600); out.sinAcepto = await toast(c);
await c.ev('document.getElementById("acepto").click(); true');
await seguir(c, 1500);
out.final = await pantalla(c);
await m('9-recibido');
out.recibido = await c.ev('document.getElementById("pfPantalla").innerText.replace(/\\n+/g," / ") + " || " + document.getElementById("pfPie").innerText.replace(/\\n+/g," / ")');
out.avisoFinal = (await avisos(c)).map(a => [a.estado_curacion, a.operacion, a.moneda, a.precio, a.plazo, a.disponible_desde, (a.caracteristicas||[]).join('+'), a.fotos.length, a.amoblado].join(' | '));
out.eventos = await c.ev('JSON.parse(localStorage.getItem("bp_eventos")||"[]").map(e=>e.evento).join(",")');
out.errores = c.errores; out.consola = c.consola;
console.log(JSON.stringify(out, null, 1)); await c.cerrar(); process.exit(0);
